modLoader="javafml"
loaderVersion="*"
license="All rights reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Ore%20Discovery%20Broadcast"
logoFile="icon.png"

[[mods]]
modId="orediscoverybroadcast"
version="2.1"
displayName="Ore Discovery Broadcast"
displayURL="https://serilum.com/mod/ore-discovery-broadcast"
authors="Rick South"
description='''Broadcasts a message to the server whenever a player finds an ore vein. With config options and a blacklist.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Alister, Andrean Olgo, aternosorg, BirdieMiner, Cherriesaurus, Jack, Jeremy Langford, Michael W. S., pepe1191, Shana Gitnick, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate. Appreciate it! <3   
'''

[[dependencies.orediscoverybroadcast]]
    modId="collective"
    type="required"
    versionRange="[7.54,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.orediscoverybroadcast]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "orediscoverybroadcast.mixins.json"